### ISSUE TITLE
What is the hash in local css and js?

### ISSUE THREAD

**Issue by dschulten** [gustafnk/microservice-websites#26]
When discussing local css and js, you have a [hash] in several locations. E.g.

"…which after inclusion becomes:
 
    <link rel="stylesheet" href="/shopping-cart/component/style-[hash].css">
    <script src="/shopping-cart/component/script-[hash].js"></script>

What does this [hash] mean?

**Comment by gustafnk** [comment]
Hi Dietrich and thank you for your question :)

The `[hash]` is a "cache bust", i.e. something that identifies the resource in a unique way, so that if the resource content changes (newly deployed code JS/CSS) the filename changes as well. That way, we can cache JS/CSS forever.

It's nothing special about this architecture – I'd say it's a common pattern for caching some types of web resources.

I think the first online article that mentions this approach is [Two Simple Rules for HTTP Caching]( https://blog.httpwatch.com/2007/12/10/two-simple-rules-for-http-caching/), but they do the cache busting with a query parameter instead.

Does that make sense?

Cheers
Gustaf

**Comment by dschulten** [comment]
Ah, ok. I like the fact that the article you mention also considers Last-Modified as part of the solution. You mention once that little-loader could load cache-busted scripts. Maybe a short section on cache-busting would be in order. Are pull requests welcome?

**Comment by gustafnk** [comment]
Yes. Would you like to create an issue "Write short section on cache-busting"? (So that you are the reporter of the issue).

And, yes, pull request are welcome :)

**Comment by gustafnk** [comment]
Clarified: https://gustafnk.github.io/microservice-websites/#local-stylesheets-and-scripts

**Comment by gustafnk** [comment]
Also, removed little-loader from this section, since I believe ESI is a better mechanism for this in general.
